name = "jev-lean"
version = "0.1.0"
defaultTargets = ["JevLean"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[require]]
name = "pantograph"
git = "https://github.com/stanford-centaur/Pantograph.git"
rev = "7076ab3632b5de67a4f83ab259b23b37acaea1d0"

[[lean_lib]]
name = "JevLean"
